# Generated by Django 5.1.2 on 2025-06-21 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('tipo_evento', models.CharField(choices=[('ENTRENAMIENTO', 'Entrenamiento'), ('PARTIDO', 'Partido'), ('REUNION', 'Reunión'), ('EVENTO', 'Evento especial')], max_length=20)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.club')),
            ],
        ),
    ]
