# Generated by Django 5.1.7 on 2025-06-25 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0004_atleta_categoria'),
        ('clubes', '0002_remove_administradorclub_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_clubes', to='atletas.atleta')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atletas_inscritos', to='clubes.club')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('atleta',), name='unique_atleta_activo')],
            },
        ),
    ]
