# Generated by Django 5.1.2 on 2025-06-27 04:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0004_atleta_categoria'),
        ('clubes', '0003_clubatleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='serial_club',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False),
        ),
        migrations.AlterField(
            model_name='clubatleta',
            name='atleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_atletas', to='atletas.atleta'),
        ),
        migrations.AlterField(
            model_name='clubatleta',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubes_disponibles', to='clubes.club'),
        ),
    ]
