# Generated by Django 5.1.2 on 2025-06-27 04:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0004_club_serial_club_alter_clubatleta_atleta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='serial_club',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
