# Generated by Django 5.1.7 on 2025-07-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0005_alter_club_serial_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubatleta',
            name='cuota_mensual',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
            preserve_default=False,
        ),
    ]
