# Generated by Django 5.1.2 on 2025-07-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0006_clubatleta_cuota_mensual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubatleta',
            name='cuota_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
