# Generated by Django 5.1.7 on 2025-07-01 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubes', '0006_clubatleta_cuota_mensual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago_Mensualida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_pago', models.DateField(auto_now_add=True)),
                ('monto', models.FloatField()),
                ('mes_correspondiente', models.DateField()),
                ('foto_comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('confirmacion', models.BooleanField(default=False)),
                ('atleta_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.clubatleta')),
            ],
            options={
                'db_table': 'Pago_Mensualidades',
            },
        ),
        migrations.CreateModel(
            name='PagoInscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_pago', models.DateField(auto_now_add=True)),
                ('monto', models.FloatField()),
                ('foto_comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('confirmacion', models.BooleanField(default=False)),
                ('atleta_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.clubatleta')),
            ],
            options={
                'db_table': 'Pago_Inscripciones',
            },
        ),
    ]
