# Generated by Django 5.1.2 on 2025-06-21 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AtletaDeporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_habilidad', models.CharField(blank=True, choices=[('PRINCIPIANTE', 'Principiante'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado'), ('PROFESIONAL', 'Profesional')], max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atletas.atleta')),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.deporte')),
            ],
            options={
                'unique_together': {('atleta', 'deporte')},
            },
        ),
    ]
