# Generated by Django 5.1.2 on 2025-06-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0002_alter_atletadeporte_unique_together_atleta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
