# Generated by Django 5.1.2 on 2025-06-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0003_atleta_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
