# Generated by Django 5.1.2 on 2025-06-21 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atletas', '0001_initial'),
        ('clubes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtletaClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cuota_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atletas.atleta')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.club')),
            ],
            options={
                'unique_together': {('atleta', 'club')},
            },
        ),
        migrations.CreateModel(
            name='MembresiaClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('BASICO', 'Básico'), ('ESTANDAR', 'Estándar'), ('PREMIUM', 'Premium')], max_length=20)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_proximo_pago', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.club')),
            ],
        ),
        migrations.CreateModel(
            name='PagoMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('metodo_pago', models.CharField(choices=[('TARJETA', 'Tarjeta de crédito/débito'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('EFECTIVO', 'Efectivo')], max_length=20)),
                ('referencia', models.CharField(max_length=100)),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membresias.membresiaclub')),
            ],
        ),
        migrations.CreateModel(
            name='PagoMensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('mes_correspondiente', models.DateField()),
                ('confirmado', models.BooleanField(default=False)),
                ('atleta_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membresias.atletaclub')),
            ],
        ),
    ]
