# Generated by Django 5.1.7 on 2025-07-01 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0006_clubatleta_cuota_mensual'),
        ('membresias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagomensualidad',
            name='atleta_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.clubatleta'),
        ),
        migrations.DeleteModel(
            name='AtletaClub',
        ),
    ]
